{"stats": {"errors": 0, "failures": 3, "passes": 0, "skipped": 0, "encoding": "UTF-8", "total": 3}, "results": [{"classname": "index_test:BlockTest", "name": "test_bip141", "time": 0.0003936290740966797, "type": "failure", "errtype": "builtins.AssertionError", "message": "None is not true", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/jonastest00/bips-jsong-programming-blockchain-demo/test/index_test.py\", line 30, in test_bip141\n    self.assertTrue(block.bip141())\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 682, in assertTrue\n    raise self.failureException(msg)\nAssertionError: None is not true\n"}, {"classname": "index_test:BlockTest", "name": "test_bip9", "time": 0.0001881122589111328, "type": "failure", "errtype": "builtins.AssertionError", "message": "None is not true", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/jonastest00/bips-jsong-programming-blockchain-demo/test/index_test.py\", line 10, in test_bip9\n    self.assertTrue(block.bip9())\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 682, in assertTrue\n    raise self.failureException(msg)\nAssertionError: None is not true\n"}, {"classname": "index_test:BlockTest", "name": "test_bip91", "time": 0.00020933151245117188, "type": "failure", "errtype": "builtins.AssertionError", "message": "None is not true", "tb": "Traceback (most recent call last):\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 59, in testPartExecutor\n    yield\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 605, in run\n    testMethod()\n  File \"/home/jonastest00/bips-jsong-programming-blockchain-demo/test/index_test.py\", line 20, in test_bip91\n    self.assertTrue(block.bip91())\n  File \"/opt/conda/lib/python3.6/unittest/case.py\", line 682, in assertTrue\n    raise self.failureException(msg)\nAssertionError: None is not true\n"}]}